name: instagram_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  instagram_share:
    path: ../instagram_share
  path: ^1.9.0
  collection: ^1.18.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  mongo_dart: ^0.10.0
  synchronized: ^3.1.0+1
  dart_jsonwebtoken: ^2.13.0
  mailer: ^6.1.0
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
